// 카페 데이터 Part2 - 강남구 삼성동
window.cafePlacesPart2 = [
    {
        name: "삼성정원카페",
        address: "서울시 강남구 삼성동 111-11",
        phone: "02-1111-1111",
        category: "일반 카페",
        rating: 4.3,
        price_range: "4천원~8천원",
        description: "삼성동의 대표 일반 카페입니다.",
        features: ["일반 카페", "삼성", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "삼성향기카페",
        address: "서울시 강남구 삼성동 222-22",
        phone: "02-2222-2222",
        category: "디저트 카페",
        rating: 4.4,
        price_range: "5천원~9천원",
        description: "삼성동의 향기 디저트카페입니다.",
        features: ["디저트 카페", "삼성", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "삼성궁전카페",
        address: "서울시 강남구 삼성동 333-33",
        phone: "02-3333-3333",
        category: "베이커리 카페",
        rating: 4.2,
        price_range: "3천원~7천원",
        description: "삼성동의 맛있는 베이커리 카페입니다.",
        features: ["베이커리 카페", "삼성", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "삼성고운카페",
        address: "서울시 강남구 삼성동 444-44",
        phone: "02-4444-4444",
        category: "루프탑 카페",
        rating: 4.5,
        price_range: "6천원~1만원",
        description: "삼성동의 고급 루프탑카페입니다.",
        features: ["루프탑 카페", "삼성", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "삼성맛나카페",
        address: "서울시 강남구 삼성동 555-55",
        phone: "02-5555-5555",
        category: "테마 카페",
        rating: 4.1,
        price_range: "4천원~8천원",
        description: "삼성동의 트렌디한 테마 카페입니다.",
        features: ["테마 카페", "삼성", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "삼성정원티룸",
        address: "서울시 강남구 삼성동 666-66",
        phone: "02-6666-6666",
        category: "티룸",
        rating: 4.3,
        price_range: "5천원~9천원",
        description: "삼성동의 대표 티룸입니다.",
        features: ["티룸", "삼성", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "삼성향기브런치",
        address: "서울시 강남구 삼성동 777-77",
        phone: "02-7777-7777",
        category: "브런치 카페",
        rating: 4.4,
        price_range: "8천원~1만2천원",
        description: "삼성동의 향기 브런치카페입니다.",
        features: ["브런치 카페", "삼성", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "점심",
        purpose: "데이트"
    },
    {
        name: "삼성궁전스터디",
        address: "서울시 강남구 삼성동 888-88",
        phone: "02-8888-8888",
        category: "스터디 카페",
        rating: 4.2,
        price_range: "3천원~7천원",
        description: "삼성동의 맛있는 스터디카페입니다.",
        features: ["스터디 카페", "삼성", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "삼성고운프리미엄",
        address: "서울시 강남구 삼성동 999-99",
        phone: "02-9999-9999",
        category: "프리미엄 카페",
        rating: 4.6,
        price_range: "8천원~1만2천원",
        description: "삼성동의 고급 프리미엄 카페입니다.",
        features: ["프리미엄 카페", "삼성", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "삼성맛나24시간",
        address: "서울시 강남구 삼성동 101-10",
        phone: "02-1010-1010",
        category: "24시간 카페",
        rating: 4.0,
        price_range: "3천원~7천원",
        description: "삼성동의 트렌디한 24시간 카페입니다.",
        features: ["24시간 카페", "삼성", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addCafePlacesPart2() {
    console.log('카페 장소 데이터 Part2 로드 중...');
    console.log('총 추가된 카페 수:', cafePlacesPart2.length);
}