// 마지막 추가 지역들 데이터 (상수·합정, 연희동, 청량리, 가로수길, DDP 동대문 패션타운)
const additionalPlacesPart8 = [
    // 마포구 상수 한식 10개
    {
        name: "상수정원",
        address: "서울시 마포구 상수동 111-11",
        phone: "02-1111-1101",
        category: "닭갈비",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "상수의 대표 닭갈비 전문점입니다.",
        features: ["닭갈비", "상수", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "상수향기",
        address: "서울시 마포구 상수동 222-22",
        phone: "02-2222-1102",
        category: "보쌈",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "상수의 인기 보쌈 전문점입니다.",
        features: ["보쌈", "상수", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "상수궁전",
        address: "서울시 마포구 상수동 333-33",
        phone: "02-3333-1103",
        category: "족발",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "상수의 맛있는 족발 전문점입니다.",
        features: ["족발", "상수", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "상수고운",
        address: "서울시 마포구 상수동 444-44",
        phone: "02-4444-1104",
        category: "김치전골",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "상수의 고급 김치전골 전문점입니다.",
        features: ["김치전골", "상수", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "상수맛나",
        address: "서울시 마포구 상수동 555-55",
        phone: "02-5555-1105",
        category: "버섯전골",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "상수의 합리적인 버섯전골 전문점입니다.",
        features: ["버섯전골", "상수", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "상수정원2",
        address: "서울시 마포구 상수동 666-66",
        phone: "02-6666-1106",
        category: "김치찌개",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "상수의 대표 김치찌개 전문점입니다.",
        features: ["김치찌개", "상수", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "상수향기2",
        address: "서울시 마포구 상수동 777-77",
        phone: "02-7777-1107",
        category: "된장찌개",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "상수의 인기 된장찌개 전문점입니다.",
        features: ["된장찌개", "상수", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "상수궁전2",
        address: "서울시 마포구 상수동 888-88",
        phone: "02-8888-1108",
        category: "순두부찌개",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "상수의 맛있는 순두부찌개 전문점입니다.",
        features: ["순두부찌개", "상수", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "상수고운2",
        address: "서울시 마포구 상수동 999-99",
        phone: "02-9999-1109",
        category: "순대국",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "상수의 고급 순대국 전문점입니다.",
        features: ["순대국", "상수", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "상수맛나2",
        address: "서울시 마포구 상수동 101-10",
        phone: "02-1010-1110",
        category: "콩나물국밥",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "상수의 합리적인 콩나물국밥 전문점입니다.",
        features: ["콩나물국밥", "상수", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 마포구 합정 한식 10개
    {
        name: "합정정원",
        address: "서울시 마포구 합정동 111-11",
        phone: "02-1111-1201",
        category: "해물파전",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "합정의 대표 해물파전 전문점입니다.",
        features: ["해물파전", "합정", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "합정향기",
        address: "서울시 마포구 합정동 222-22",
        phone: "02-2222-1202",
        category: "감자전",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "합정의 인기 감자전 전문점입니다.",
        features: ["감자전", "합정", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "합정궁전",
        address: "서울시 마포구 합정동 333-33",
        phone: "02-3333-1203",
        category: "아구찜",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "합정의 맛있는 아구찜 전문점입니다.",
        features: ["아구찜", "합정", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "합정고운",
        address: "서울시 마포구 합정동 444-44",
        phone: "02-4444-1204",
        category: "해물찜",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "합정의 고급 해물찜 전문점입니다.",
        features: ["해물찜", "합정", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "합정맛나",
        address: "서울시 마포구 합정동 555-55",
        phone: "02-5555-1205",
        category: "감자탕",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "합정의 합리적인 감자탕 전문점입니다.",
        features: ["감자탕", "합정", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "합정정원2",
        address: "서울시 마포구 합정동 666-66",
        phone: "02-6666-1206",
        category: "활어회",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "합정의 대표 활어회 전문점입니다.",
        features: ["활어회", "합정", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "합정향기2",
        address: "서울시 마포구 합정동 777-77",
        phone: "02-7777-1207",
        category: "모듬회",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "합정의 인기 모듬회 전문점입니다.",
        features: ["모듬회", "합정", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "합정궁전2",
        address: "서울시 마포구 합정동 888-88",
        phone: "02-8888-1208",
        category: "백반",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "합정의 맛있는 백반 전문점입니다.",
        features: ["백반", "합정", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "합정고운2",
        address: "서울시 마포구 합정동 999-99",
        phone: "02-9999-1209",
        category: "라면+김밥 세트",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "합정의 고급 라면+김밥 세트 전문점입니다.",
        features: ["라면+김밥 세트", "합정", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "합정맛나2",
        address: "서울시 마포구 합정동 101-10",
        phone: "02-1010-1210",
        category: "떡볶이",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "합정의 합리적인 떡볶이 전문점입니다.",
        features: ["떡볶이", "합정", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 서대문구 연희동 한식 10개
    {
        name: "연희동정원",
        address: "서울시 서대문구 연희동 111-11",
        phone: "02-1111-1301",
        category: "전주비빔밥",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "연희동의 대표 전주비빔밥 전문점입니다.",
        features: ["전주비빔밥", "연희동", "단체석", "친구"],
        region: "서대문구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "연희동향기",
        address: "서울시 서대문구 연희동 222-22",
        phone: "02-2222-1302",
        category: "진주냉면",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "연희동의 인기 진주냉면 전문점입니다.",
        features: ["진주냉면", "연희동", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희동궁전",
        address: "서울시 서대문구 연희동 333-33",
        phone: "02-3333-1303",
        category: "평양냉면",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "연희동의 맛있는 평양냉면 전문점입니다.",
        features: ["평양냉면", "연희동", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "연희동고운",
        address: "서울시 서대문구 연희동 444-44",
        phone: "02-4444-1304",
        category: "부산돼지국밥",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "연희동의 고급 부산돼지국밥 전문점입니다.",
        features: ["부산돼지국밥", "연희동", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희동맛나",
        address: "서울시 서대문구 연희동 555-55",
        phone: "02-5555-1305",
        category: "비빔밥",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "연희동의 합리적인 비빔밥 전문점입니다.",
        features: ["비빔밥", "연희동", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "연희동정원2",
        address: "서울시 서대문구 연희동 666-66",
        phone: "02-6666-1306",
        category: "설렁탕",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "연희동의 대표 설렁탕 전문점입니다.",
        features: ["설렁탕", "연희동", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "연희동향기2",
        address: "서울시 서대문구 연희동 777-77",
        phone: "02-7777-1307",
        category: "곰탕",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "연희동의 인기 곰탕 전문점입니다.",
        features: ["곰탕", "연희동", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희동궁전2",
        address: "서울시 서대문구 연희동 888-88",
        phone: "02-8888-1308",
        category: "갈비탕",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "연희동의 맛있는 갈비탕 전문점입니다.",
        features: ["갈비탕", "연희동", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "연희동고운2",
        address: "서울시 서대문구 연희동 999-99",
        phone: "02-9999-1309",
        category: "불고기",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "연희동의 고급 불고기 전문점입니다.",
        features: ["불고기", "연희동", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희동맛나2",
        address: "서울시 서대문구 연희동 101-10",
        phone: "02-1010-1310",
        category: "삼겹살",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "연희동의 합리적인 삼겹살 전문점입니다.",
        features: ["삼겹살", "연희동", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addAdditionalPlacesPart8() {
    console.log('추가 장소 데이터 Part8 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlacesPart8.length);
}
