// 각 지역별 5개씩 추가할 장소 데이터
const additionalPlaces = [
    // 강남구 역삼동 한정식 5개
    {
        name: "역삼정원",
        address: "서울시 강남구 역삼동 111-11",
        phone: "02-1111-1111",
        category: "비빔밥",
        rating: 4.3,
        price_range: "1만8천원~2만5천원",
        description: "역삼동의 대표 비빔밥 전문점입니다.",
        features: ["비빔밥", "역삼", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "역삼향기",
        address: "서울시 강남구 역삼동 222-22",
        phone: "02-2222-2222",
        category: "설렁탕",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "역삼동의 인기 설렁탕 전문점입니다.",
        features: ["설렁탕", "역삼", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "역삼궁전",
        address: "서울시 강남구 역삼동 333-33",
        phone: "02-3333-3333",
        category: "곰탕",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "역삼동의 맛있는 곰탕 전문점입니다.",
        features: ["곰탕", "역삼", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "역삼고운",
        address: "서울시 강남구 역삼동 444-44",
        phone: "02-4444-4444",
        category: "갈비탕",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "역삼동의 고급 갈비탕 전문점입니다.",
        features: ["갈비탕", "역삼", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "역삼맛나",
        address: "서울시 강남구 역삼동 555-55",
        phone: "02-5555-5555",
        category: "불고기",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "역삼동의 합리적인 불고기 전문점입니다.",
        features: ["불고기", "역삼", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 강남구 삼성동 한정식 5개
    {
        name: "삼성정원",
        address: "서울시 강남구 삼성동 111-11",
        phone: "02-1111-1112",
        category: "삼겹살",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "삼성동의 대표 삼겹살 전문점입니다.",
        features: ["삼겹살", "삼성", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "삼성향기",
        address: "서울시 강남구 삼성동 222-22",
        phone: "02-2222-2223",
        category: "갈비구이",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "삼성동의 인기 갈비구이 전문점입니다.",
        features: ["갈비구이", "삼성", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "삼성궁전",
        address: "서울시 강남구 삼성동 333-33",
        phone: "02-3333-3334",
        category: "닭갈비",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "삼성동의 고급 닭갈비 전문점입니다.",
        features: ["닭갈비", "삼성", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "삼성고운",
        address: "서울시 강남구 삼성동 444-44",
        phone: "02-4444-4445",
        category: "보쌈",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "삼성동의 맛있는 보쌈 전문점입니다.",
        features: ["보쌈", "삼성", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "삼성맛나",
        address: "서울시 강남구 삼성동 555-55",
        phone: "02-5555-5556",
        category: "족발",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "삼성동의 합리적인 족발 전문점입니다.",
        features: ["족발", "삼성", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 강남구 신사동 한정식 5개
    {
        name: "신사정원",
        address: "서울시 강남구 신사동 111-11",
        phone: "02-1111-1113",
        category: "김치전골",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "신사동의 대표 김치전골 전문점입니다.",
        features: ["김치전골", "신사", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "신사향기",
        address: "서울시 강남구 신사동 222-22",
        phone: "02-2222-2224",
        category: "버섯전골",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "신사동의 인기 버섯전골 전문점입니다.",
        features: ["버섯전골", "신사", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "신사궁전",
        address: "서울시 강남구 신사동 333-33",
        phone: "02-3333-3335",
        category: "김치찌개",
        rating: 4.6,
        price_range: "2만2천원~2만9천원",
        description: "신사동의 고급 김치찌개 전문점입니다.",
        features: ["김치찌개", "신사", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "신사고운",
        address: "서울시 강남구 신사동 444-44",
        phone: "02-4444-4446",
        category: "된장찌개",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "신사동의 맛있는 된장찌개 전문점입니다.",
        features: ["된장찌개", "신사", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "신사맛나",
        address: "서울시 강남구 신사동 555-55",
        phone: "02-5555-5557",
        category: "순두부찌개",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "신사동의 합리적인 순두부찌개 전문점입니다.",
        features: ["순두부찌개", "신사", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 강남구 압구정동 한정식 5개
    {
        name: "압구정정원",
        address: "서울시 강남구 압구정동 111-11",
        phone: "02-1111-1114",
        category: "순대국",
        rating: 4.6,
        price_range: "2만1천원~2만8천원",
        description: "압구정동의 대표 순대국 전문점입니다.",
        features: ["순대국", "압구정", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "압구정향기",
        address: "서울시 강남구 압구정동 222-22",
        phone: "02-2222-2225",
        category: "콩나물국밥",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "압구정동의 인기 콩나물국밥 전문점입니다.",
        features: ["콩나물국밥", "압구정", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "압구정궁전",
        address: "서울시 강남구 압구정동 333-33",
        phone: "02-3333-3336",
        category: "해물파전",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "압구정동의 맛있는 해물파전 전문점입니다.",
        features: ["해물파전", "압구정", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "압구정고운",
        address: "서울시 강남구 압구정동 444-44",
        phone: "02-4444-4447",
        category: "감자전",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "압구정동의 합리적인 감자전 전문점입니다.",
        features: ["감자전", "압구정", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "압구정맛나",
        address: "서울시 강남구 압구정동 555-55",
        phone: "02-5555-5558",
        category: "아구찜",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "압구정동의 저렴한 아구찜 전문점입니다.",
        features: ["아구찜", "압구정", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 강남구 청담동 한정식 5개
    {
        name: "청담정원",
        address: "서울시 강남구 청담동 111-11",
        phone: "02-1111-1115",
        category: "해물찜",
        rating: 4.7,
        price_range: "2만2천원~2만9천원",
        description: "청담동의 대표 해물찜 전문점입니다.",
        features: ["해물찜", "청담", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "청담향기",
        address: "서울시 강남구 청담동 222-22",
        phone: "02-2222-2226",
        category: "감자탕",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "청담동의 인기 감자탕 전문점입니다.",
        features: ["감자탕", "청담", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "청담궁전",
        address: "서울시 강남구 청담동 333-33",
        phone: "02-3333-3337",
        category: "활어회",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "청담동의 맛있는 활어회 전문점입니다.",
        features: ["활어회", "청담", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "청담고운",
        address: "서울시 강남구 청담동 444-44",
        phone: "02-4444-4448",
        category: "모듬회",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "청담동의 합리적인 모듬회 전문점입니다.",
        features: ["모듬회", "청담", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "청담맛나",
        address: "서울시 강남구 청담동 555-55",
        phone: "02-5555-5559",
        category: "백반",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "청담동의 저렴한 백반 전문점입니다.",
        features: ["백반", "청담", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 마포구 홍대 한정식 5개
    {
        name: "홍대정원",
        address: "서울시 마포구 홍대입구역 111-11",
        phone: "02-1111-2001",
        category: "라면+김밥 세트",
        rating: 4.3,
        price_range: "1만8천원~2만5천원",
        description: "홍대의 대표 라면+김밥 세트 전문점입니다.",
        features: ["라면+김밥 세트", "홍대", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "홍대향기",
        address: "서울시 마포구 홍대입구역 222-22",
        phone: "02-2222-2002",
        category: "떡볶이",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "홍대의 인기 떡볶이 전문점입니다.",
        features: ["떡볶이", "홍대", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "홍대궁전",
        address: "서울시 마포구 홍대입구역 333-33",
        phone: "02-3333-2003",
        category: "전주비빔밥",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "홍대의 맛있는 전주비빔밥 전문점입니다.",
        features: ["전주비빔밥", "홍대", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "홍대고운",
        address: "서울시 마포구 홍대입구역 444-44",
        phone: "02-4444-2004",
        category: "진주냉면",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "홍대의 고급 진주냉면 전문점입니다.",
        features: ["진주냉면", "홍대", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "홍대맛나",
        address: "서울시 마포구 홍대입구역 555-55",
        phone: "02-5555-2005",
        category: "평양냉면",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "홍대의 합리적인 평양냉면 전문점입니다.",
        features: ["평양냉면", "홍대", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 마포구 합정 한정식 5개
    {
        name: "합정한정식1",
        address: "서울시 마포구 합정동 111-11",
        phone: "02-1111-2006",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "합정의 대표 한정식 전문점입니다.",
        features: ["한정식", "합정", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "합정한정식2",
        address: "서울시 마포구 합정동 222-22",
        phone: "02-2222-2007",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "합정의 인기 한정식집입니다.",
        features: ["한정식", "합정", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "합정한정식3",
        address: "서울시 마포구 합정동 333-33",
        phone: "02-3333-2008",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "합정의 고급 한정식 전문점입니다.",
        features: ["한정식", "합정", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "합정한정식4",
        address: "서울시 마포구 합정동 444-44",
        phone: "02-4444-2009",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "합정의 맛있는 한정식집입니다.",
        features: ["한정식", "합정", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "합정한정식5",
        address: "서울시 마포구 합정동 555-55",
        phone: "02-5555-2010",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "합정의 합리적인 한정식집입니다.",
        features: ["한정식", "합정", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 마포구 망원 한정식 5개
    {
        name: "망원한정식1",
        address: "서울시 마포구 망원동 111-11",
        phone: "02-1111-2011",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만5천원",
        description: "망원의 대표 한정식 전문점입니다.",
        features: ["한정식", "망원", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "망원한정식2",
        address: "서울시 마포구 망원동 222-22",
        phone: "02-2222-2012",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "망원의 인기 한정식집입니다.",
        features: ["한정식", "망원", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "망원한정식3",
        address: "서울시 마포구 망원동 333-33",
        phone: "02-3333-2013",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "망원의 맛있는 한정식집입니다.",
        features: ["한정식", "망원", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "망원한정식4",
        address: "서울시 마포구 망원동 444-44",
        phone: "02-4444-2014",
        category: "한정식",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "망원의 고급 한정식 전문점입니다.",
        features: ["한정식", "망원", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "망원한정식5",
        address: "서울시 마포구 망원동 555-55",
        phone: "02-5555-2015",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "망원의 합리적인 한정식집입니다.",
        features: ["한정식", "망원", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 마포구 상수 한정식 5개
    {
        name: "상수한정식1",
        address: "서울시 마포구 상수동 111-11",
        phone: "02-1111-2016",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "상수의 대표 한정식 전문점입니다.",
        features: ["한정식", "상수", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "상수한정식2",
        address: "서울시 마포구 상수동 222-22",
        phone: "02-2222-2017",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "상수의 인기 한정식집입니다.",
        features: ["한정식", "상수", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "상수한정식3",
        address: "서울시 마포구 상수동 333-33",
        phone: "02-3333-2018",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "상수의 고급 한정식 전문점입니다.",
        features: ["한정식", "상수", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "상수한정식4",
        address: "서울시 마포구 상수동 444-44",
        phone: "02-4444-2019",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "상수의 맛있는 한정식집입니다.",
        features: ["한정식", "상수", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "상수한정식5",
        address: "서울시 마포구 상수동 555-55",
        phone: "02-5555-2020",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "상수의 합리적인 한정식집입니다.",
        features: ["한정식", "상수", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 마포구 마포 한정식 5개
    {
        name: "마포한정식1",
        address: "서울시 마포구 마포동 111-11",
        phone: "02-1111-2021",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만5천원",
        description: "마포의 대표 한정식 전문점입니다.",
        features: ["한정식", "마포", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "마포한정식2",
        address: "서울시 마포구 마포동 222-22",
        phone: "02-2222-2022",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "마포의 인기 한정식집입니다.",
        features: ["한정식", "마포", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "마포한정식3",
        address: "서울시 마포구 마포동 333-33",
        phone: "02-3333-2023",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "마포의 맛있는 한정식집입니다.",
        features: ["한정식", "마포", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "마포한정식4",
        address: "서울시 마포구 마포동 444-44",
        phone: "02-4444-2024",
        category: "한정식",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "마포의 고급 한정식 전문점입니다.",
        features: ["한정식", "마포", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "마포한정식5",
        address: "서울시 마포구 마포동 555-55",
        phone: "02-5555-2025",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "마포의 합리적인 한정식집입니다.",
        features: ["한정식", "마포", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 마포구 공덕 한정식 5개
    {
        name: "공덕한정식1",
        address: "서울시 마포구 공덕동 111-11",
        phone: "02-1111-2026",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "공덕의 대표 한정식 전문점입니다.",
        features: ["한정식", "공덕", "단체석", "가족"],
        region: "마포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "공덕한정식2",
        address: "서울시 마포구 공덕동 222-22",
        phone: "02-2222-2027",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "공덕의 인기 한정식집입니다.",
        features: ["한정식", "공덕", "단체석", "친구"],
        region: "마포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "공덕한정식3",
        address: "서울시 마포구 공덕동 333-33",
        phone: "02-3333-2028",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "공덕의 고급 한정식 전문점입니다.",
        features: ["한정식", "공덕", "고급", "단체석"],
        region: "마포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "공덕한정식4",
        address: "서울시 마포구 공덕동 444-44",
        phone: "02-4444-2029",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "공덕의 맛있는 한정식집입니다.",
        features: ["한정식", "공덕", "단체석", "데이트"],
        region: "마포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "공덕한정식5",
        address: "서울시 마포구 공덕동 555-55",
        phone: "02-5555-2030",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "공덕의 합리적인 한정식집입니다.",
        features: ["한정식", "공덕", "단체석", "친구"],
        region: "마포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 영등포구 여의도 한정식 5개
    {
        name: "여의도한정식1",
        address: "서울시 영등포구 여의도동 111-11",
        phone: "02-1111-3001",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "여의도의 대표 한정식 전문점입니다.",
        features: ["한정식", "여의도", "단체석", "가족"],
        region: "영등포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "여의도한정식2",
        address: "서울시 영등포구 여의도동 222-22",
        phone: "02-2222-3002",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "여의도의 인기 한정식집입니다.",
        features: ["한정식", "여의도", "단체석", "친구"],
        region: "영등포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "여의도한정식3",
        address: "서울시 영등포구 여의도동 333-33",
        phone: "02-3333-3003",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "여의도의 고급 한정식 전문점입니다.",
        features: ["한정식", "여의도", "고급", "단체석"],
        region: "영등포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "여의도한정식4",
        address: "서울시 영등포구 여의도동 444-44",
        phone: "02-4444-3004",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "여의도의 맛있는 한정식집입니다.",
        features: ["한정식", "여의도", "단체석", "데이트"],
        region: "영등포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "여의도한정식5",
        address: "서울시 영등포구 여의도동 555-55",
        phone: "02-5555-3005",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "여의도의 합리적인 한정식집입니다.",
        features: ["한정식", "여의도", "단체석", "친구"],
        region: "영등포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 영등포구 영등포 한정식 5개
    {
        name: "영등포한정식1",
        address: "서울시 영등포구 영등포동 111-11",
        phone: "02-1111-3006",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만5천원",
        description: "영등포의 대표 한정식 전문점입니다.",
        features: ["한정식", "영등포", "단체석", "친구"],
        region: "영등포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "영등포한정식2",
        address: "서울시 영등포구 영등포동 222-22",
        phone: "02-2222-3007",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "영등포의 인기 한정식집입니다.",
        features: ["한정식", "영등포", "단체석", "데이트"],
        region: "영등포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "영등포한정식3",
        address: "서울시 영등포구 영등포동 333-33",
        phone: "02-3333-3008",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "영등포의 맛있는 한정식집입니다.",
        features: ["한정식", "영등포", "단체석", "가족"],
        region: "영등포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "영등포한정식4",
        address: "서울시 영등포구 영등포동 444-44",
        phone: "02-4444-3009",
        category: "한정식",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "영등포의 고급 한정식 전문점입니다.",
        features: ["한정식", "영등포", "고급", "단체석"],
        region: "영등포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "영등포한정식5",
        address: "서울시 영등포구 영등포동 555-55",
        phone: "02-5555-3010",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "영등포의 합리적인 한정식집입니다.",
        features: ["한정식", "영등포", "단체석", "친구"],
        region: "영등포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 영등포구 당산 한정식 5개
    {
        name: "당산한정식1",
        address: "서울시 영등포구 당산동 111-11",
        phone: "02-1111-3011",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "당산의 대표 한정식 전문점입니다.",
        features: ["한정식", "당산", "단체석", "가족"],
        region: "영등포구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "당산한정식2",
        address: "서울시 영등포구 당산동 222-22",
        phone: "02-2222-3012",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "당산의 인기 한정식집입니다.",
        features: ["한정식", "당산", "단체석", "친구"],
        region: "영등포구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "당산한정식3",
        address: "서울시 영등포구 당산동 333-33",
        phone: "02-3333-3013",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "당산의 고급 한정식 전문점입니다.",
        features: ["한정식", "당산", "고급", "단체석"],
        region: "영등포구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "당산한정식4",
        address: "서울시 영등포구 당산동 444-44",
        phone: "02-4444-3014",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "당산의 맛있는 한정식집입니다.",
        features: ["한정식", "당산", "단체석", "데이트"],
        region: "영등포구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "당산한정식5",
        address: "서울시 영등포구 당산동 555-55",
        phone: "02-5555-3015",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "당산의 합리적인 한정식집입니다.",
        features: ["한정식", "당산", "단체석", "친구"],
        region: "영등포구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 종로구 종로 한정식 5개
    {
        name: "종로한정식1",
        address: "서울시 종로구 종로1가 111-11",
        phone: "02-1111-4001",
        category: "한정식",
        rating: 4.5,
        price_range: "2만원~2만8천원",
        description: "종로의 대표 한정식 전문점입니다.",
        features: ["한정식", "종로", "단체석", "가족"],
        region: "종로구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "종로한정식2",
        address: "서울시 종로구 종로1가 222-22",
        phone: "02-2222-4002",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "종로의 인기 한정식집입니다.",
        features: ["한정식", "종로", "단체석", "친구"],
        region: "종로구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "종로한정식3",
        address: "서울시 종로구 종로1가 333-33",
        phone: "02-3333-4003",
        category: "한정식",
        rating: 4.6,
        price_range: "2만2천원~2만9천원",
        description: "종로의 고급 한정식 전문점입니다.",
        features: ["한정식", "종로", "고급", "단체석"],
        region: "종로구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "종로한정식4",
        address: "서울시 종로구 종로1가 444-44",
        phone: "02-4444-4004",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "종로의 맛있는 한정식집입니다.",
        features: ["한정식", "종로", "단체석", "데이트"],
        region: "종로구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "종로한정식5",
        address: "서울시 종로구 종로1가 555-55",
        phone: "02-5555-4005",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "종로의 합리적인 한정식집입니다.",
        features: ["한정식", "종로", "단체석", "친구"],
        region: "종로구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 종로구 광화문 한정식 5개
    {
        name: "광화문한정식1",
        address: "서울시 종로구 세종대로 111-11",
        phone: "02-1111-4006",
        category: "한정식",
        rating: 4.6,
        price_range: "2만2천원~3만원",
        description: "광화문의 대표 한정식 전문점입니다.",
        features: ["한정식", "광화문", "고급", "단체석"],
        region: "종로구",
        budget: "비싼",
        people: "4-5",
        mood: "고급스러운",
        time: "저녁",
        purpose: "가족모임"
    },
    {
        name: "광화문한정식2",
        address: "서울시 종로구 세종대로 222-22",
        phone: "02-2222-4007",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "광화문의 인기 한정식집입니다.",
        features: ["한정식", "광화문", "단체석", "데이트"],
        region: "종로구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "광화문한정식3",
        address: "서울시 종로구 세종대로 333-33",
        phone: "02-3333-4008",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "광화문의 맛있는 한정식집입니다.",
        features: ["한정식", "광화문", "단체석", "가족"],
        region: "종로구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "광화문한정식4",
        address: "서울시 종로구 세종대로 444-44",
        phone: "02-4444-4009",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "광화문의 합리적인 한정식집입니다.",
        features: ["한정식", "광화문", "단체석", "친구"],
        region: "종로구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "광화문한정식5",
        address: "서울시 종로구 세종대로 555-55",
        phone: "02-5555-4010",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "광화문의 저렴한 한정식집입니다.",
        features: ["한정식", "광화문", "단체석", "친구"],
        region: "종로구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 종로구 인사동 한정식 5개
    {
        name: "인사동한정식1",
        address: "서울시 종로구 인사동 111-11",
        phone: "02-1111-4011",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "인사동의 대표 한정식 전문점입니다.",
        features: ["한정식", "인사동", "전통", "단체석"],
        region: "종로구",
        budget: "적당한",
        people: "2-3",
        mood: "조용한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "인사동한정식2",
        address: "서울시 종로구 인사동 222-22",
        phone: "02-2222-4012",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "인사동의 인기 한정식집입니다.",
        features: ["한정식", "인사동", "단체석", "친구"],
        region: "종로구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "인사동한정식3",
        address: "서울시 종로구 인사동 333-33",
        phone: "02-3333-4013",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "인사동의 고급 한정식 전문점입니다.",
        features: ["한정식", "인사동", "고급", "단체석"],
        region: "종로구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "인사동한정식4",
        address: "서울시 종로구 인사동 444-44",
        phone: "02-4444-4014",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "인사동의 맛있는 한정식집입니다.",
        features: ["한정식", "인사동", "단체석", "가족"],
        region: "종로구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "인사동한정식5",
        address: "서울시 종로구 인사동 555-55",
        phone: "02-5555-4015",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "인사동의 합리적인 한정식집입니다.",
        features: ["한정식", "인사동", "단체석", "친구"],
        region: "종로구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 중구 동대문 한정식 5개
    {
        name: "동대문한정식1",
        address: "서울시 중구 을지로6가 111-11",
        phone: "02-1111-5001",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "동대문의 대표 한정식 전문점입니다.",
        features: ["한정식", "동대문", "단체석", "친구"],
        region: "중구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "동대문한정식2",
        address: "서울시 중구 을지로6가 222-22",
        phone: "02-2222-5002",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "동대문의 인기 한정식집입니다.",
        features: ["한정식", "동대문", "단체석", "데이트"],
        region: "중구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "동대문한정식3",
        address: "서울시 중구 을지로6가 333-33",
        phone: "02-3333-5003",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "동대문의 맛있는 한정식집입니다.",
        features: ["한정식", "동대문", "단체석", "가족"],
        region: "중구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "동대문한정식4",
        address: "서울시 중구 을지로6가 444-44",
        phone: "02-4444-5004",
        category: "한정식",
        rating: 4.5,
        price_range: "2만원~2만7천원",
        description: "동대문의 고급 한정식 전문점입니다.",
        features: ["한정식", "동대문", "고급", "단체석"],
        region: "중구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "동대문한정식5",
        address: "서울시 중구 을지로6가 555-55",
        phone: "02-5555-5005",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "동대문의 합리적인 한정식집입니다.",
        features: ["한정식", "동대문", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 중구 명동 한정식 5개
    {
        name: "명동한정식1",
        address: "서울시 중구 명동 111-11",
        phone: "02-1111-5006",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만5천원",
        description: "명동의 대표 한정식 전문점입니다.",
        features: ["한정식", "명동", "단체석", "데이트"],
        region: "중구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "명동한정식2",
        address: "서울시 중구 명동 222-22",
        phone: "02-2222-5007",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만6천원",
        description: "명동의 인기 한정식집입니다.",
        features: ["한정식", "명동", "단체석", "가족"],
        region: "중구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "명동한정식3",
        address: "서울시 중구 명동 333-33",
        phone: "02-3333-5008",
        category: "한정식",
        rating: 4.5,
        price_range: "2만1천원~2만8천원",
        description: "명동의 고급 한정식 전문점입니다.",
        features: ["한정식", "명동", "고급", "단체석"],
        region: "중구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "명동한정식4",
        address: "서울시 중구 명동 444-44",
        phone: "02-4444-5009",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "명동의 맛있는 한정식집입니다.",
        features: ["한정식", "명동", "단체석", "친구"],
        region: "중구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "명동한정식5",
        address: "서울시 중구 명동 555-55",
        phone: "02-5555-5010",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "명동의 합리적인 한정식집입니다.",
        features: ["한정식", "명동", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    // 중구 충무로 한정식 5개
    {
        name: "충무로한정식1",
        address: "서울시 중구 충무로 111-11",
        phone: "02-1111-5011",
        category: "한정식",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "충무로의 대표 한정식 전문점입니다.",
        features: ["한정식", "충무로", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "충무로한정식2",
        address: "서울시 중구 충무로 222-22",
        phone: "02-2222-5012",
        category: "한정식",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "충무로의 인기 한정식집입니다.",
        features: ["한정식", "충무로", "단체석", "데이트"],
        region: "중구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "충무로한정식3",
        address: "서울시 중구 충무로 333-33",
        phone: "02-3333-5013",
        category: "한정식",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "충무로의 맛있는 한정식집입니다.",
        features: ["한정식", "충무로", "단체석", "가족"],
        region: "중구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "충무로한정식4",
        address: "서울시 중구 충무로 444-44",
        phone: "02-4444-5014",
        category: "한정식",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "충무로의 고급 한정식 전문점입니다.",
        features: ["한정식", "충무로", "고급", "단체석"],
        region: "중구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "충무로한정식5",
        address: "서울시 중구 충무로 555-55",
        phone: "02-5555-5015",
        category: "한정식",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "충무로의 저렴한 한정식집입니다.",
        features: ["한정식", "충무로", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

// 추가 데이터를 chat.html에 적용하는 함수
function addAdditionalPlaces() {
    console.log('추가 장소 데이터 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlaces.length);
    
    // 기존 allPlaces 배열에 추가
    if (typeof allPlaces !== 'undefined') {
        allPlaces.push(...additionalPlaces);
        console.log('추가 완료! 총 장소 수:', allPlaces.length);
    } else {
        console.log('allPlaces 배열을 찾을 수 없습니다.');
    }
}

// 페이지 로드 시 자동 실행
if (typeof window !== 'undefined') {
    window.addAdditionalPlaces = addAdditionalPlaces;
}
