// 마지막 추가 지역들 데이터 Part3 (남대문시장, 잠실 석촌호수, 문래동, 을지로, 혜화·대학로)
const additionalPlacesPart10 = [
    // 중구 남대문시장 한식 10개
    {
        name: "남대문시장정원",
        address: "서울시 중구 남대문시장 111-11",
        phone: "02-1111-1701",
        category: "삼겹살",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "남대문시장의 대표 삼겹살 전문점입니다.",
        features: ["삼겹살", "남대문시장", "단체석", "친구"],
        region: "중구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "남대문시장향기",
        address: "서울시 중구 남대문시장 222-22",
        phone: "02-2222-1702",
        category: "갈비구이",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "남대문시장의 인기 갈비구이 전문점입니다.",
        features: ["갈비구이", "남대문시장", "단체석", "데이트"],
        region: "중구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "남대문시장궁전",
        address: "서울시 중구 남대문시장 333-33",
        phone: "02-3333-1703",
        category: "닭갈비",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "남대문시장의 맛있는 닭갈비 전문점입니다.",
        features: ["닭갈비", "남대문시장", "단체석", "가족"],
        region: "중구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "남대문시장고운",
        address: "서울시 중구 남대문시장 444-44",
        phone: "02-4444-1704",
        category: "보쌈",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "남대문시장의 고급 보쌈 전문점입니다.",
        features: ["보쌈", "남대문시장", "고급", "단체석"],
        region: "중구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "남대문시장맛나",
        address: "서울시 중구 남대문시장 555-55",
        phone: "02-5555-1705",
        category: "족발",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "남대문시장의 합리적인 족발 전문점입니다.",
        features: ["족발", "남대문시장", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "남대문시장정원2",
        address: "서울시 중구 남대문시장 666-66",
        phone: "02-6666-1706",
        category: "김치전골",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "남대문시장의 대표 김치전골 전문점입니다.",
        features: ["김치전골", "남대문시장", "단체석", "가족"],
        region: "중구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "남대문시장향기2",
        address: "서울시 중구 남대문시장 777-77",
        phone: "02-7777-1707",
        category: "버섯전골",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "남대문시장의 인기 버섯전골 전문점입니다.",
        features: ["버섯전골", "남대문시장", "단체석", "데이트"],
        region: "중구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "남대문시장궁전2",
        address: "서울시 중구 남대문시장 888-88",
        phone: "02-8888-1708",
        category: "김치찌개",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "남대문시장의 맛있는 김치찌개 전문점입니다.",
        features: ["김치찌개", "남대문시장", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "남대문시장고운2",
        address: "서울시 중구 남대문시장 999-99",
        phone: "02-9999-1709",
        category: "된장찌개",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "남대문시장의 고급 된장찌개 전문점입니다.",
        features: ["된장찌개", "남대문시장", "고급", "단체석"],
        region: "중구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "남대문시장맛나2",
        address: "서울시 중구 남대문시장 101-10",
        phone: "02-1010-1710",
        category: "순두부찌개",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "남대문시장의 합리적인 순두부찌개 전문점입니다.",
        features: ["순두부찌개", "남대문시장", "단체석", "친구"],
        region: "중구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 송파구 잠실 석촌호수 한식 10개
    {
        name: "석촌호수정원",
        address: "서울시 송파구 잠실동 석촌호수 111-11",
        phone: "02-1111-1801",
        category: "순대국",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "잠실 석촌호수의 대표 순대국 전문점입니다.",
        features: ["순대국", "석촌호수", "단체석", "친구"],
        region: "송파구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "석촌호수향기",
        address: "서울시 송파구 잠실동 석촌호수 222-22",
        phone: "02-2222-1802",
        category: "콩나물국밥",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "잠실 석촌호수의 인기 콩나물국밥 전문점입니다.",
        features: ["콩나물국밥", "석촌호수", "단체석", "데이트"],
        region: "송파구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "석촌호수궁전",
        address: "서울시 송파구 잠실동 석촌호수 333-33",
        phone: "02-3333-1803",
        category: "해물파전",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "잠실 석촌호수의 맛있는 해물파전 전문점입니다.",
        features: ["해물파전", "석촌호수", "단체석", "가족"],
        region: "송파구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "석촌호수고운",
        address: "서울시 송파구 잠실동 석촌호수 444-44",
        phone: "02-4444-1804",
        category: "감자전",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "잠실 석촌호수의 고급 감자전 전문점입니다.",
        features: ["감자전", "석촌호수", "고급", "단체석"],
        region: "송파구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "석촌호수맛나",
        address: "서울시 송파구 잠실동 석촌호수 555-55",
        phone: "02-5555-1805",
        category: "아구찜",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "잠실 석촌호수의 합리적인 아구찜 전문점입니다.",
        features: ["아구찜", "석촌호수", "단체석", "친구"],
        region: "송파구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "석촌호수정원2",
        address: "서울시 송파구 잠실동 석촌호수 666-66",
        phone: "02-6666-1806",
        category: "해물찜",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "잠실 석촌호수의 대표 해물찜 전문점입니다.",
        features: ["해물찜", "석촌호수", "단체석", "가족"],
        region: "송파구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "석촌호수향기2",
        address: "서울시 송파구 잠실동 석촌호수 777-77",
        phone: "02-7777-1807",
        category: "감자탕",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "잠실 석촌호수의 인기 감자탕 전문점입니다.",
        features: ["감자탕", "석촌호수", "단체석", "데이트"],
        region: "송파구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "석촌호수궁전2",
        address: "서울시 송파구 잠실동 석촌호수 888-88",
        phone: "02-8888-1808",
        category: "활어회",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "잠실 석촌호수의 맛있는 활어회 전문점입니다.",
        features: ["활어회", "석촌호수", "단체석", "친구"],
        region: "송파구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "석촌호수고운2",
        address: "서울시 송파구 잠실동 석촌호수 999-99",
        phone: "02-9999-1809",
        category: "모듬회",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "잠실 석촌호수의 고급 모듬회 전문점입니다.",
        features: ["모듬회", "석촌호수", "고급", "단체석"],
        region: "송파구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "석촌호수맛나2",
        address: "서울시 송파구 잠실동 석촌호수 101-10",
        phone: "02-1010-1810",
        category: "백반",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "잠실 석촌호수의 합리적인 백반 전문점입니다.",
        features: ["백반", "석촌호수", "단체석", "친구"],
        region: "송파구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addAdditionalPlacesPart10() {
    console.log('추가 장소 데이터 Part10 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlacesPart10.length);
}
