// 마지막 추가 지역들 데이터 Part2 (청량리, 가로수길, DDP 동대문 패션타운, 남대문시장)
const additionalPlacesPart9 = [
    // 동대문구 청량리 한식 10개
    {
        name: "청량리정원",
        address: "서울시 동대문구 청량리동 111-11",
        phone: "02-1111-1401",
        category: "갈비구이",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "청량리의 대표 갈비구이 전문점입니다.",
        features: ["갈비구이", "청량리", "단체석", "친구"],
        region: "동대문구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "청량리향기",
        address: "서울시 동대문구 청량리동 222-22",
        phone: "02-2222-1402",
        category: "닭갈비",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "청량리의 인기 닭갈비 전문점입니다.",
        features: ["닭갈비", "청량리", "단체석", "데이트"],
        region: "동대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "청량리궁전",
        address: "서울시 동대문구 청량리동 333-33",
        phone: "02-3333-1403",
        category: "보쌈",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "청량리의 맛있는 보쌈 전문점입니다.",
        features: ["보쌈", "청량리", "단체석", "가족"],
        region: "동대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "청량리고운",
        address: "서울시 동대문구 청량리동 444-44",
        phone: "02-4444-1404",
        category: "족발",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "청량리의 고급 족발 전문점입니다.",
        features: ["족발", "청량리", "고급", "단체석"],
        region: "동대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "청량리맛나",
        address: "서울시 동대문구 청량리동 555-55",
        phone: "02-5555-1405",
        category: "김치전골",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "청량리의 합리적인 김치전골 전문점입니다.",
        features: ["김치전골", "청량리", "단체석", "친구"],
        region: "동대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "청량리정원2",
        address: "서울시 동대문구 청량리동 666-66",
        phone: "02-6666-1406",
        category: "버섯전골",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "청량리의 대표 버섯전골 전문점입니다.",
        features: ["버섯전골", "청량리", "단체석", "가족"],
        region: "동대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "청량리향기2",
        address: "서울시 동대문구 청량리동 777-77",
        phone: "02-7777-1407",
        category: "김치찌개",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "청량리의 인기 김치찌개 전문점입니다.",
        features: ["김치찌개", "청량리", "단체석", "데이트"],
        region: "동대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "청량리궁전2",
        address: "서울시 동대문구 청량리동 888-88",
        phone: "02-8888-1408",
        category: "된장찌개",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "청량리의 맛있는 된장찌개 전문점입니다.",
        features: ["된장찌개", "청량리", "단체석", "친구"],
        region: "동대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "청량리고운2",
        address: "서울시 동대문구 청량리동 999-99",
        phone: "02-9999-1409",
        category: "순두부찌개",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "청량리의 고급 순두부찌개 전문점입니다.",
        features: ["순두부찌개", "청량리", "고급", "단체석"],
        region: "동대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "청량리맛나2",
        address: "서울시 동대문구 청량리동 101-10",
        phone: "02-1010-1410",
        category: "순대국",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "청량리의 합리적인 순대국 전문점입니다.",
        features: ["순대국", "청량리", "단체석", "친구"],
        region: "동대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 강남구 가로수길 한식 10개
    {
        name: "가로수길정원",
        address: "서울시 강남구 신사동 가로수길 111-11",
        phone: "02-1111-1501",
        category: "콩나물국밥",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "가로수길의 대표 콩나물국밥 전문점입니다.",
        features: ["콩나물국밥", "가로수길", "단체석", "친구"],
        region: "강남구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "가로수길향기",
        address: "서울시 강남구 신사동 가로수길 222-22",
        phone: "02-2222-1502",
        category: "해물파전",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "가로수길의 인기 해물파전 전문점입니다.",
        features: ["해물파전", "가로수길", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "가로수길궁전",
        address: "서울시 강남구 신사동 가로수길 333-33",
        phone: "02-3333-1503",
        category: "감자전",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "가로수길의 맛있는 감자전 전문점입니다.",
        features: ["감자전", "가로수길", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "가로수길고운",
        address: "서울시 강남구 신사동 가로수길 444-44",
        phone: "02-4444-1504",
        category: "아구찜",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "가로수길의 고급 아구찜 전문점입니다.",
        features: ["아구찜", "가로수길", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "가로수길맛나",
        address: "서울시 강남구 신사동 가로수길 555-55",
        phone: "02-5555-1505",
        category: "해물찜",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "가로수길의 합리적인 해물찜 전문점입니다.",
        features: ["해물찜", "가로수길", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "가로수길정원2",
        address: "서울시 강남구 신사동 가로수길 666-66",
        phone: "02-6666-1506",
        category: "감자탕",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "가로수길의 대표 감자탕 전문점입니다.",
        features: ["감자탕", "가로수길", "단체석", "가족"],
        region: "강남구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "가로수길향기2",
        address: "서울시 강남구 신사동 가로수길 777-77",
        phone: "02-7777-1507",
        category: "활어회",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "가로수길의 인기 활어회 전문점입니다.",
        features: ["활어회", "가로수길", "단체석", "데이트"],
        region: "강남구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "가로수길궁전2",
        address: "서울시 강남구 신사동 가로수길 888-88",
        phone: "02-8888-1508",
        category: "모듬회",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "가로수길의 맛있는 모듬회 전문점입니다.",
        features: ["모듬회", "가로수길", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "가로수길고운2",
        address: "서울시 강남구 신사동 가로수길 999-99",
        phone: "02-9999-1509",
        category: "백반",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "가로수길의 고급 백반 전문점입니다.",
        features: ["백반", "가로수길", "고급", "단체석"],
        region: "강남구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "가로수길맛나2",
        address: "서울시 강남구 신사동 가로수길 101-10",
        phone: "02-1010-1510",
        category: "라면+김밥 세트",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "가로수길의 합리적인 라면+김밥 세트 전문점입니다.",
        features: ["라면+김밥 세트", "가로수길", "단체석", "친구"],
        region: "강남구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 동대문구 DDP 동대문 패션타운 한식 10개
    {
        name: "DDP정원",
        address: "서울시 동대문구 을지로6가 DDP 111-11",
        phone: "02-1111-1601",
        category: "떡볶이",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "DDP 동대문 패션타운의 대표 떡볶이 전문점입니다.",
        features: ["떡볶이", "DDP", "단체석", "친구"],
        region: "동대문구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "DDP향기",
        address: "서울시 동대문구 을지로6가 DDP 222-22",
        phone: "02-2222-1602",
        category: "전주비빔밥",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "DDP 동대문 패션타운의 인기 전주비빔밥 전문점입니다.",
        features: ["전주비빔밥", "DDP", "단체석", "데이트"],
        region: "동대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "DDP궁전",
        address: "서울시 동대문구 을지로6가 DDP 333-33",
        phone: "02-3333-1603",
        category: "진주냉면",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "DDP 동대문 패션타운의 맛있는 진주냉면 전문점입니다.",
        features: ["진주냉면", "DDP", "단체석", "가족"],
        region: "동대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "DDP고운",
        address: "서울시 동대문구 을지로6가 DDP 444-44",
        phone: "02-4444-1604",
        category: "평양냉면",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "DDP 동대문 패션타운의 고급 평양냉면 전문점입니다.",
        features: ["평양냉면", "DDP", "고급", "단체석"],
        region: "동대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "DDP맛나",
        address: "서울시 동대문구 을지로6가 DDP 555-55",
        phone: "02-5555-1605",
        category: "부산돼지국밥",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "DDP 동대문 패션타운의 합리적인 부산돼지국밥 전문점입니다.",
        features: ["부산돼지국밥", "DDP", "단체석", "친구"],
        region: "동대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "DDP정원2",
        address: "서울시 동대문구 을지로6가 DDP 666-66",
        phone: "02-6666-1606",
        category: "비빔밥",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "DDP 동대문 패션타운의 대표 비빔밥 전문점입니다.",
        features: ["비빔밥", "DDP", "단체석", "가족"],
        region: "동대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "DDP향기2",
        address: "서울시 동대문구 을지로6가 DDP 777-77",
        phone: "02-7777-1607",
        category: "설렁탕",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "DDP 동대문 패션타운의 인기 설렁탕 전문점입니다.",
        features: ["설렁탕", "DDP", "단체석", "데이트"],
        region: "동대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "DDP궁전2",
        address: "서울시 동대문구 을지로6가 DDP 888-88",
        phone: "02-8888-1608",
        category: "곰탕",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "DDP 동대문 패션타운의 맛있는 곰탕 전문점입니다.",
        features: ["곰탕", "DDP", "단체석", "친구"],
        region: "동대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "DDP고운2",
        address: "서울시 동대문구 을지로6가 DDP 999-99",
        phone: "02-9999-1609",
        category: "갈비탕",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "DDP 동대문 패션타운의 고급 갈비탕 전문점입니다.",
        features: ["갈비탕", "DDP", "고급", "단체석"],
        region: "동대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "DDP맛나2",
        address: "서울시 동대문구 을지로6가 DDP 101-10",
        phone: "02-1010-1610",
        category: "불고기",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "DDP 동대문 패션타운의 합리적인 불고기 전문점입니다.",
        features: ["불고기", "DDP", "단체석", "친구"],
        region: "동대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addAdditionalPlacesPart9() {
    console.log('추가 장소 데이터 Part9 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlacesPart9.length);
}
