// 추가 지역들 데이터 (노원/중계, 신촌/연희/이대, 목동/신정, 상계/수유/쌍문)
const additionalPlacesPart3 = [
    // 노원구 노원 한식 10개
    {
        name: "노원정원",
        address: "서울시 노원구 노원동 111-11",
        phone: "02-1111-1001",
        category: "비빔밥",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "노원의 대표 비빔밥 전문점입니다.",
        features: ["비빔밥", "노원", "단체석", "친구"],
        region: "노원구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "노원향기",
        address: "서울시 노원구 노원동 222-22",
        phone: "02-2222-1002",
        category: "설렁탕",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "노원의 인기 설렁탕 전문점입니다.",
        features: ["설렁탕", "노원", "단체석", "데이트"],
        region: "노원구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "노원궁전",
        address: "서울시 노원구 노원동 333-33",
        phone: "02-3333-1003",
        category: "곰탕",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "노원의 맛있는 곰탕 전문점입니다.",
        features: ["곰탕", "노원", "단체석", "가족"],
        region: "노원구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "노원고운",
        address: "서울시 노원구 노원동 444-44",
        phone: "02-4444-1004",
        category: "갈비탕",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "노원의 고급 갈비탕 전문점입니다.",
        features: ["갈비탕", "노원", "고급", "단체석"],
        region: "노원구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "노원맛나",
        address: "서울시 노원구 노원동 555-55",
        phone: "02-5555-1005",
        category: "불고기",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "노원의 합리적인 불고기 전문점입니다.",
        features: ["불고기", "노원", "단체석", "친구"],
        region: "노원구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "노원정원2",
        address: "서울시 노원구 노원동 666-66",
        phone: "02-6666-1006",
        category: "삼겹살",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "노원의 대표 삼겹살 전문점입니다.",
        features: ["삼겹살", "노원", "단체석", "가족"],
        region: "노원구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "노원향기2",
        address: "서울시 노원구 노원동 777-77",
        phone: "02-7777-1007",
        category: "갈비구이",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "노원의 인기 갈비구이 전문점입니다.",
        features: ["갈비구이", "노원", "단체석", "데이트"],
        region: "노원구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "노원궁전2",
        address: "서울시 노원구 노원동 888-88",
        phone: "02-8888-1008",
        category: "닭갈비",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "노원의 맛있는 닭갈비 전문점입니다.",
        features: ["닭갈비", "노원", "단체석", "친구"],
        region: "노원구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "노원고운2",
        address: "서울시 노원구 노원동 999-99",
        phone: "02-9999-1009",
        category: "보쌈",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "노원의 고급 보쌈 전문점입니다.",
        features: ["보쌈", "노원", "고급", "단체석"],
        region: "노원구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "노원맛나2",
        address: "서울시 노원구 노원동 101-10",
        phone: "02-1010-1010",
        category: "족발",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "노원의 합리적인 족발 전문점입니다.",
        features: ["족발", "노원", "단체석", "친구"],
        region: "노원구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 노원구 중계 한식 10개
    {
        name: "중계정원",
        address: "서울시 노원구 중계동 111-11",
        phone: "02-1111-2001",
        category: "김치전골",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "중계의 대표 김치전골 전문점입니다.",
        features: ["김치전골", "중계", "단체석", "친구"],
        region: "노원구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "중계향기",
        address: "서울시 노원구 중계동 222-22",
        phone: "02-2222-2002",
        category: "버섯전골",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "중계의 인기 버섯전골 전문점입니다.",
        features: ["버섯전골", "중계", "단체석", "데이트"],
        region: "노원구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "중계궁전",
        address: "서울시 노원구 중계동 333-33",
        phone: "02-3333-2003",
        category: "김치찌개",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "중계의 맛있는 김치찌개 전문점입니다.",
        features: ["김치찌개", "중계", "단체석", "가족"],
        region: "노원구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "중계고운",
        address: "서울시 노원구 중계동 444-44",
        phone: "02-4444-2004",
        category: "된장찌개",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "중계의 고급 된장찌개 전문점입니다.",
        features: ["된장찌개", "중계", "고급", "단체석"],
        region: "노원구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "중계맛나",
        address: "서울시 노원구 중계동 555-55",
        phone: "02-5555-2005",
        category: "순두부찌개",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "중계의 합리적인 순두부찌개 전문점입니다.",
        features: ["순두부찌개", "중계", "단체석", "친구"],
        region: "노원구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "중계정원2",
        address: "서울시 노원구 중계동 666-66",
        phone: "02-6666-2006",
        category: "순대국",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "중계의 대표 순대국 전문점입니다.",
        features: ["순대국", "중계", "단체석", "가족"],
        region: "노원구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "중계향기2",
        address: "서울시 노원구 중계동 777-77",
        phone: "02-7777-2007",
        category: "콩나물국밥",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "중계의 인기 콩나물국밥 전문점입니다.",
        features: ["콩나물국밥", "중계", "단체석", "데이트"],
        region: "노원구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "중계궁전2",
        address: "서울시 노원구 중계동 888-88",
        phone: "02-8888-2008",
        category: "해물파전",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "중계의 맛있는 해물파전 전문점입니다.",
        features: ["해물파전", "중계", "단체석", "친구"],
        region: "노원구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "중계고운2",
        address: "서울시 노원구 중계동 999-99",
        phone: "02-9999-2009",
        category: "감자전",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "중계의 고급 감자전 전문점입니다.",
        features: ["감자전", "중계", "고급", "단체석"],
        region: "노원구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "중계맛나2",
        address: "서울시 노원구 중계동 101-10",
        phone: "02-1010-2010",
        category: "아구찜",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "중계의 합리적인 아구찜 전문점입니다.",
        features: ["아구찜", "중계", "단체석", "친구"],
        region: "노원구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addAdditionalPlacesPart3() {
    console.log('추가 장소 데이터 Part3 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlacesPart3.length);
}
