// 추가 지역들 데이터 Part2 (신촌/연희/이대, 목동/신정, 상계/수유/쌍문)
const additionalPlacesPart4 = [
    // 서대문구 신촌 한식 10개
    {
        name: "신촌정원",
        address: "서울시 서대문구 신촌동 111-11",
        phone: "02-1111-3001",
        category: "해물찜",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "신촌의 대표 해물찜 전문점입니다.",
        features: ["해물찜", "신촌", "단체석", "친구"],
        region: "서대문구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "신촌향기",
        address: "서울시 서대문구 신촌동 222-22",
        phone: "02-2222-3002",
        category: "감자탕",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "신촌의 인기 감자탕 전문점입니다.",
        features: ["감자탕", "신촌", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "신촌궁전",
        address: "서울시 서대문구 신촌동 333-33",
        phone: "02-3333-3003",
        category: "활어회",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "신촌의 맛있는 활어회 전문점입니다.",
        features: ["활어회", "신촌", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "신촌고운",
        address: "서울시 서대문구 신촌동 444-44",
        phone: "02-4444-3004",
        category: "모듬회",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "신촌의 고급 모듬회 전문점입니다.",
        features: ["모듬회", "신촌", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "신촌맛나",
        address: "서울시 서대문구 신촌동 555-55",
        phone: "02-5555-3005",
        category: "백반",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "신촌의 합리적인 백반 전문점입니다.",
        features: ["백반", "신촌", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "신촌정원2",
        address: "서울시 서대문구 신촌동 666-66",
        phone: "02-6666-3006",
        category: "라면+김밥 세트",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "신촌의 대표 라면+김밥 세트 전문점입니다.",
        features: ["라면+김밥 세트", "신촌", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "신촌향기2",
        address: "서울시 서대문구 신촌동 777-77",
        phone: "02-7777-3007",
        category: "떡볶이",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "신촌의 인기 떡볶이 전문점입니다.",
        features: ["떡볶이", "신촌", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "신촌궁전2",
        address: "서울시 서대문구 신촌동 888-88",
        phone: "02-8888-3008",
        category: "전주비빔밥",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "신촌의 맛있는 전주비빔밥 전문점입니다.",
        features: ["전주비빔밥", "신촌", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "신촌고운2",
        address: "서울시 서대문구 신촌동 999-99",
        phone: "02-9999-3009",
        category: "진주냉면",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "신촌의 고급 진주냉면 전문점입니다.",
        features: ["진주냉면", "신촌", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "신촌맛나2",
        address: "서울시 서대문구 신촌동 101-10",
        phone: "02-1010-3010",
        category: "평양냉면",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "신촌의 합리적인 평양냉면 전문점입니다.",
        features: ["평양냉면", "신촌", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 서대문구 연희 한식 10개
    {
        name: "연희정원",
        address: "서울시 서대문구 연희동 111-11",
        phone: "02-1111-4001",
        category: "부산돼지국밥",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "연희의 대표 부산돼지국밥 전문점입니다.",
        features: ["부산돼지국밥", "연희", "단체석", "친구"],
        region: "서대문구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "연희향기",
        address: "서울시 서대문구 연희동 222-22",
        phone: "02-2222-4002",
        category: "비빔밥",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "연희의 인기 비빔밥 전문점입니다.",
        features: ["비빔밥", "연희", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희궁전",
        address: "서울시 서대문구 연희동 333-33",
        phone: "02-3333-4003",
        category: "설렁탕",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "연희의 맛있는 설렁탕 전문점입니다.",
        features: ["설렁탕", "연희", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "연희고운",
        address: "서울시 서대문구 연희동 444-44",
        phone: "02-4444-4004",
        category: "곰탕",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "연희의 고급 곰탕 전문점입니다.",
        features: ["곰탕", "연희", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희맛나",
        address: "서울시 서대문구 연희동 555-55",
        phone: "02-5555-4005",
        category: "갈비탕",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "연희의 합리적인 갈비탕 전문점입니다.",
        features: ["갈비탕", "연희", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "연희정원2",
        address: "서울시 서대문구 연희동 666-66",
        phone: "02-6666-4006",
        category: "불고기",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "연희의 대표 불고기 전문점입니다.",
        features: ["불고기", "연희", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "연희향기2",
        address: "서울시 서대문구 연희동 777-77",
        phone: "02-7777-4007",
        category: "삼겹살",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "연희의 인기 삼겹살 전문점입니다.",
        features: ["삼겹살", "연희", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희궁전2",
        address: "서울시 서대문구 연희동 888-88",
        phone: "02-8888-4008",
        category: "갈비구이",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "연희의 맛있는 갈비구이 전문점입니다.",
        features: ["갈비구이", "연희", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "연희고운2",
        address: "서울시 서대문구 연희동 999-99",
        phone: "02-9999-4009",
        category: "닭갈비",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "연희의 고급 닭갈비 전문점입니다.",
        features: ["닭갈비", "연희", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "연희맛나2",
        address: "서울시 서대문구 연희동 101-10",
        phone: "02-1010-4010",
        category: "보쌈",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "연희의 합리적인 보쌈 전문점입니다.",
        features: ["보쌈", "연희", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addAdditionalPlacesPart4() {
    console.log('추가 장소 데이터 Part4 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlacesPart4.length);
}
