// 추가 지역들 데이터 Part3 (이대, 목동/신정, 상계/수유/쌍문)
const additionalPlacesPart5 = [
    // 서대문구 이대 한식 10개
    {
        name: "이대정원",
        address: "서울시 서대문구 이대동 111-11",
        phone: "02-1111-5001",
        category: "족발",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "이대의 대표 족발 전문점입니다.",
        features: ["족발", "이대", "단체석", "친구"],
        region: "서대문구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "이대향기",
        address: "서울시 서대문구 이대동 222-22",
        phone: "02-2222-5002",
        category: "김치전골",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "이대의 인기 김치전골 전문점입니다.",
        features: ["김치전골", "이대", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "이대궁전",
        address: "서울시 서대문구 이대동 333-33",
        phone: "02-3333-5003",
        category: "버섯전골",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "이대의 맛있는 버섯전골 전문점입니다.",
        features: ["버섯전골", "이대", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "이대고운",
        address: "서울시 서대문구 이대동 444-44",
        phone: "02-4444-5004",
        category: "김치찌개",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "이대의 고급 김치찌개 전문점입니다.",
        features: ["김치찌개", "이대", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "이대맛나",
        address: "서울시 서대문구 이대동 555-55",
        phone: "02-5555-5005",
        category: "된장찌개",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "이대의 합리적인 된장찌개 전문점입니다.",
        features: ["된장찌개", "이대", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "이대정원2",
        address: "서울시 서대문구 이대동 666-66",
        phone: "02-6666-5006",
        category: "순두부찌개",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "이대의 대표 순두부찌개 전문점입니다.",
        features: ["순두부찌개", "이대", "단체석", "가족"],
        region: "서대문구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "이대향기2",
        address: "서울시 서대문구 이대동 777-77",
        phone: "02-7777-5007",
        category: "순대국",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "이대의 인기 순대국 전문점입니다.",
        features: ["순대국", "이대", "단체석", "데이트"],
        region: "서대문구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "이대궁전2",
        address: "서울시 서대문구 이대동 888-88",
        phone: "02-8888-5008",
        category: "콩나물국밥",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "이대의 맛있는 콩나물국밥 전문점입니다.",
        features: ["콩나물국밥", "이대", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "이대고운2",
        address: "서울시 서대문구 이대동 999-99",
        phone: "02-9999-5009",
        category: "해물파전",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "이대의 고급 해물파전 전문점입니다.",
        features: ["해물파전", "이대", "고급", "단체석"],
        region: "서대문구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "이대맛나2",
        address: "서울시 서대문구 이대동 101-10",
        phone: "02-1010-5010",
        category: "감자전",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "이대의 합리적인 감자전 전문점입니다.",
        features: ["감자전", "이대", "단체석", "친구"],
        region: "서대문구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },

    // 양천구 목동 한식 10개
    {
        name: "목동정원",
        address: "서울시 양천구 목동 111-11",
        phone: "02-1111-6001",
        category: "아구찜",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "목동의 대표 아구찜 전문점입니다.",
        features: ["아구찜", "목동", "단체석", "친구"],
        region: "양천구",
        budget: "적당한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "목동향기",
        address: "서울시 양천구 목동 222-22",
        phone: "02-2222-6002",
        category: "해물찜",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "목동의 인기 해물찜 전문점입니다.",
        features: ["해물찜", "목동", "단체석", "데이트"],
        region: "양천구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "목동궁전",
        address: "서울시 양천구 목동 333-33",
        phone: "02-3333-6003",
        category: "감자탕",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "목동의 맛있는 감자탕 전문점입니다.",
        features: ["감자탕", "목동", "단체석", "가족"],
        region: "양천구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "목동고운",
        address: "서울시 양천구 목동 444-44",
        phone: "02-4444-6004",
        category: "활어회",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "목동의 고급 활어회 전문점입니다.",
        features: ["활어회", "목동", "고급", "단체석"],
        region: "양천구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "목동맛나",
        address: "서울시 양천구 목동 555-55",
        phone: "02-5555-6005",
        category: "모듬회",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "목동의 합리적인 모듬회 전문점입니다.",
        features: ["모듬회", "목동", "단체석", "친구"],
        region: "양천구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "목동정원2",
        address: "서울시 양천구 목동 666-66",
        phone: "02-6666-6006",
        category: "백반",
        rating: 4.2,
        price_range: "1만7천원~2만3천원",
        description: "목동의 대표 백반 전문점입니다.",
        features: ["백반", "목동", "단체석", "가족"],
        region: "양천구",
        budget: "적당한",
        people: "4-5",
        mood: "편안한",
        time: "점심",
        purpose: "가족모임"
    },
    {
        name: "목동향기2",
        address: "서울시 양천구 목동 777-77",
        phone: "02-7777-6007",
        category: "라면+김밥 세트",
        rating: 4.3,
        price_range: "1만8천원~2만4천원",
        description: "목동의 인기 라면+김밥 세트 전문점입니다.",
        features: ["라면+김밥 세트", "목동", "단체석", "데이트"],
        region: "양천구",
        budget: "적당한",
        people: "2-3",
        mood: "로맨틱한",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "목동궁전2",
        address: "서울시 양천구 목동 888-88",
        phone: "02-8888-6008",
        category: "떡볶이",
        rating: 4.1,
        price_range: "1만6천원~2만2천원",
        description: "목동의 맛있는 떡볶이 전문점입니다.",
        features: ["떡볶이", "목동", "단체석", "친구"],
        region: "양천구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    },
    {
        name: "목동고운2",
        address: "서울시 양천구 목동 999-99",
        phone: "02-9999-6009",
        category: "전주비빔밥",
        rating: 4.4,
        price_range: "1만9천원~2만5천원",
        description: "목동의 고급 전주비빔밥 전문점입니다.",
        features: ["전주비빔밥", "목동", "고급", "단체석"],
        region: "양천구",
        budget: "비싼",
        people: "2-3",
        mood: "고급스러운",
        time: "저녁",
        purpose: "데이트"
    },
    {
        name: "목동맛나2",
        address: "서울시 양천구 목동 101-10",
        phone: "02-1010-6010",
        category: "진주냉면",
        rating: 4.0,
        price_range: "1만5천원~2만1천원",
        description: "목동의 합리적인 진주냉면 전문점입니다.",
        features: ["진주냉면", "목동", "단체석", "친구"],
        region: "양천구",
        budget: "저렴한",
        people: "3-4",
        mood: "활발한",
        time: "점심",
        purpose: "친구모임"
    }
];

function addAdditionalPlacesPart5() {
    console.log('추가 장소 데이터 Part5 로드 중...');
    console.log('총 추가할 장소 수:', additionalPlacesPart5.length);
}
